### ISSUE TITLE
Error in PCA analysis

### ISSUE THREAD

**Issue by JohnReid** [gcyuan/SCUBA#1]
Hi, I've tried running SCUBA on the Guo and Deng data. I get the same error message in both cases.

```
>> RNAseq_preprocess('deng2014');
>> SCUBA('deng2014')
??? Error using ==> mtimes
Inner matrix dimensions must agree.

Error in ==> pca_analysis at 18
s_all = expr_all * c;

Error in ==> SCUBA at 27
pca_analysis(dataset);

>> 
```

I think I have everything installed correctly. I'm using the latest commit from github. Do you know what might be going wrong?

**Comment by eugeniomarco** [comment]
Hi John,

Thanks for pointing this out. After installing drtoolbox and adding it to the path there was a conflict between the pca functions in the stats matlab toolbos and the drtoolbox. The code now makes sure that the stats pca function is used.

Let me know if now works for you.

Thanks,
Eugenio

**Comment by JohnReid** [comment]
Hi Eugenio,

That fixed that problem now I have [another](https://github.com/gcyuan/SCUBA/issues/2).

Thanks,
John.
