### ISSUE TITLE
Cannot find stats toolbox directory

### ISSUE THREAD

**Issue by JohnReid** [gcyuan/SCUBA#2]
When following the instructions in the README. I get the following error:

```
>> PCR_preprocess('guo2010');
>> SCUBA('guo2010')
??? Error using ==> cd
Cannot CD to /usr/local/apps/matlab-2009bsp1/toolbox/stats/stats (Name is nonexistent or not a directory).

Error in ==> pca_analysis at 11
cd(fullfile(toolboxdir('stats'),'stats'))

Error in ==> SCUBA at 27
pca_analysis(dataset);
```

I think I have the stats toolbox installed but I'm not sure where.

**Comment by JohnReid** [comment]
This directory exists `/usr/local/apps/matlab-2009bsp1/toolbox/stats`

**Comment by eugeniomarco** [comment]
Hi John,

I guess the structure of the stats toolbox has changed recently. I am busy
now, but I'll fix it later today.

Can you confirm that in /usr/local/apps/matlab-2009bsp1/toolbox/stats you
have the pca.m function?

Thanks,
Eugenio

**Comment by JohnReid** [comment]
Hi Eugenio,

I have `pcacov.m` and `pcares.m` in that directory. In matlab I get:

```
>> pca
??? Input argument "X" is undefined.

Error in ==> pca at 30
    mapping.mean = mean(X, 1);
```

Sorry if that is not very clear, I haven't used matlab before.

**Comment by eugeniomarco** [comment]
Hi John,

I have updated the pca_analysis.m function so that it uses princomp for matlab versions before R2012b, which is when pca was introduced.

The output you see when you type pca is from the drtoolbox function, which is the only pca function you have since you are using Matlab R2009b.

The code now should use princomp in your case.

Let me know if you go past that point.

Thanks,

Eugenio

**Comment by JohnReid** [comment]
Hi Eugenio,

That worked, then I got an error about `rng` which I don't think is in the R2009b version I am using. So I removed that (I assume it just seeds the RNG). Then it seemed to run an iteration and I got this error message

```
Iteration successfully ended!
??? Undefined function or method 'biograph' for input arguments of type 'cell'.

Error in ==> plotTree at 25
BG = biograph(adjMatrix, IDS);

Error in ==> refine_tree at 184
plotTree(T, dataset)

Error in ==> SCUBA at 40
refine_tree(dataset, cluster_mode);
```

Thanks for your help so far,
John.

**Comment by eugeniomarco** [comment]
Hi John,

Apparently you don't have the function biograph, which is part of the
bioinformatics toolbox. biograph is used to plot the tree.

The update now checks for the presence of the bioinformatics toolbox and
makes the plot when present.

In your case you want see the tree plotted. A text file with the
connections between the clusters will be saved though.

I hope this helps.

Regards,
Eugenio

**Comment by JohnReid** [comment]
That's great Eugenio, it seems to be getting past that now.
