### ISSUE TITLE
PCR_preprocess.m

### ISSUE THREAD

**Issue by nanp** [gcyuan/SCUBA#4]
Hello,
I am using Matlab 2015a and it give me an error running PCR_preprocess.m
I just want to warn you that I had to correct line 48 in : if exist('cell_stage'),

Best regards,
Nan.

**Comment by gcyuan** [comment]
Dear Nan,

Thank you very much for using SCUBA and letting us know the error. This has been fixed. Please feel free to contact us if you find any additional issues.

Best,
GC
