### ISSUE TITLE
Error in SCUBA

### ISSUE THREAD

**Issue by ldorozco** [gcyuan/SCUBA#6]
Hi,

When running SCUBA on qPCR data, I run into what appears to be a MATLAB bug.  Do you know what be causing this? It is strange that this does not happen when I use the 'guo2010' sample dataset. 

My input file includes a "Stage" row, but since I don't have cell stages this row is invariant. Could that be the issue. for the remaining rows I have removed invariant genes. 

Thanks,

Luz

%File head:
Cell ID 1   2   3   4
Stage   1.00    1.00    1.00    1.00
ITGAE   1.00    1.00    1.00    1.00
CD101   1.00    1.00    15.38   1.00
GZMB    1.00    12.28   12.19   13.22
TGFB1   14.81   1.00    1.00    12.89
KLRC2   8.87    1.00    12.06   7.98
GZMA    1.00    1.00    1.00    1.00
CD4 16.33   14.15   16.00   1.00
CD160   1.00    1.00    1.00    1.00

%Code
PCR_preprocess('mydata')
SCUBA('myda')

%Error
At compilation, "edges" was determined to be a variable and this variable is uninitialized. "edges" is also a function
name and previous versions of MATLAB would have called the function. However, MATLAB 7 forbids the use of the same
name in the same context as both a function and a variable.

Error in biograph.biograph (line 38)
h.edges = edges;

Error in biograph (line 207)
h = biograph.biograph(cm,ids,varargin);

Error in plotTree (line 25)
BG = biograph(adjMatrix, IDS);

Error in refine_tree (line 186)
    plotTree(T, dataset)

Error in SCUBA (line 40)

**Comment by gcyuan** [comment]
Hi,

Scuba uses the stage information to generate the lineage tree. If the stage is a constant it won't work. To solve this problem, the best strategy is to infer pseudotime like you do for RNASeq and CyTOF data. You may want to take a look at those codes to see how it's done and modify for your data. Let me know if you need help with this.

GC

**Comment by gcyuan** [comment]
Hi,

Here is another solution for your problem. 
1. leave the 'Stage' field empty
2. Run PCR_process with the option 'pseudotime_mode = 1'
   If you take a look at the PCR_process code, there are actually two input variable, and the second input corresponds to the pseudotime_mode option.

When you run this function, make sure you have downloaded all the required R functions described in the 'Systems Requirements' section

Also, make sure the 'Rscript' in the 60th line in EstimatePseudotime.m is replaced by a recognizable path for Rscript. For example, in my computer this corresponds to "C:\Program Files\R\R-3.2.5\bin\Rscript"

In the end of the preprocessing, you should get a new file called something like 'PCRPData.txt' which contains the stage information inferred by the principal curve analysis procedure. This file will be used for further bifurcation analysis.

Best,
GC
