### ISSUE TITLE
RNA-seq bulk population fractions

### ISSUE THREAD

**Issue by aopisco** [gcyuan/SCUBA#7]
Hi, I've 20 samples from bulk population + 3 fractions that have been sorted before RNA-seq. How will SCUBA perform to analyse them?

**Comment by gcyuan** [comment]
Hi, before I can answer you question, it will be great if you could provide some more details about the data and type of analysis you are trying to do.  Are you trying to analyze bulk or single cell RNAseq data?

**Comment by aopisco** [comment]
Hi, I'm trying to analyse bulk RNAseq data but from 3 sorted sub-population fractions. I have all the fractions with 6 biological replicates (18 samples total) + 2 unsorted bulk samples. Thanks!

**Comment by gcyuan** [comment]
Hi, unfortunately SCUBA is designed only to analyze single cell gene expression data. Sounds like you would need to use another software.
