### ISSUE TITLE
A permanent error 

### ISSUE THREAD

**Issue by fereshtehizadi** [gcyuan/SCUBA#8]
Hi,

Sorry, I used my own data for Scuba, without stage information that returns this error; Could you please help me in solving that?

Thanks a lot in advance 

```
>> SCUBA('deng2014')


t =

   130


t =

   131


t =

   132


t =

   133

iteration # 1

delta_mu =

     0


delta_s =

     0


delta_pa =

     0

Iteration successfully ended!
Subscript indices must either be real positive integers or logicals.

Error in refine_tree (line 231)
    fprintf(fs, '%e\n', T.mu(n, end));

Error in SCUBA (line 40)
refine_tree(dataset, cluster_mode);
 
>> 
```

**Comment by gcyuan** [comment]
Sorry about the delay in response, but I just tested SCUBA again on my computer and it worked fine. 

Looking at your output, it looks like the stage was not assigned properly. There should be 11 cell stages in total, but for some reason yours go up to over 100. Could you check by typing 

> unique(pro.cell_stage)

Also, which version of matlab you are using? 

Thanks
GC

**Comment by fereshtehizadi** [comment]
Thanks a lot,


>> unique(pro.cell_stage)

Undefined variable "pro" or class "pro.cell_stage".


my matlab is R2017a


Sorry, I have attached my input data here


https://www.dropbox.com/s/3ywa7i7ckbje1mt/My_input.txt?dl=0


Could please have a look at that? I have 8 time points and about 200 cells for each time point


Thank you

________________________________

**Comment by gcyuan** [comment]
OK. I took a quick look. I think the problem is that you named the cell stages using text labels. Try change them to numbers, such as 1, 2, 3, and 4. Also, this probably doesn’t matter, but could you sort the cells by increasing cell stage number?

Good luck.

**Comment by fereshtehizadi** [comment]
Thanks a lot for bearing with my problem kindly,


I likely edited my input file by adding stages numerically also sorting cells from stage 1 to stage 4. Now, I got different error as below, however at some level I obtained the attached plot


>> SCUBA('deng2014')


t =


     2



t =


     3



t =


     4


iteration # 1


delta_mu =


    0.8339



delta_s =


     0



delta_pa =


     0


iteration # 2


delta_mu =


     0



delta_s =


     0



delta_pa =


     0


Iteration successfully ended!

Warning: No bifurcation found.

> In bifurcation_direction (line 21)

  In SCUBA (line 48)

Index exceeds matrix dimensions.


Error in bifurcation_analysis>getScores (line 93)

results.t = T.t(parentCluster);


Error in bifurcation_analysis (line 39)

        results = getScores(bif, T, index, makePlot);


Error in SCUBA (line 52)

bifurcation_analysis(dataset)



>>



This is the like of my edited input file


https://www.dropbox.com/s/ohb64h4mya3jmuj/My_edited_input.txt?dl=0

[https://www.dropbox.com/static/images/spectrum-icons/generated/content/content-txt-large.png]<https://www.dropbox.com/s/ohb64h4mya3jmuj/My_edited_input.txt?dl=0>

My_edited_input.txt<https://www.dropbox.com/s/ohb64h4mya3jmuj/My_edited_input.txt?dl=0>
www.dropbox.com
Shared with Dropbox






Sorry, what this error mean? Could because the input is wrong or normalisation or whatever else except for that this data naturally dose not have bifurcation?


I really would like to make a cell hierarchy of my time series


Thanks a lot for any help

**Comment by gcyuan** [comment]
Actually your program finished successfully! The reason for the error
message is that the program didn't find any bifurcations, hence the second
step cannot continue.

**Comment by fereshtehizadi** [comment]
Thanks a lot

________________________________

**Comment by gcyuan** [comment]
Awesome. Thanks again for using SCUBA.
